# Generated by Django 5.0.14 on 2026-07-09 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_dokumen', models.CharField(blank=True, max_length=255)),
                ('judul', models.CharField(max_length=500)),
                ('deskripsi', models.TextField(blank=True)),
                ('file_id', models.CharField(max_length=255)),
                ('link_view', models.URLField(max_length=500)),
                ('sifat', models.CharField(choices=[('Umum', 'Umum'), ('Rahasia', 'Rahasia')], default='Umum', max_length=10)),
                ('tgl_upload', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_diunggah', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dokumen', to='arsip.kategori')),
            ],
            options={
                'verbose_name': 'Dokumen',
                'verbose_name_plural': 'Dokumen',
                'ordering': ['-tgl_upload'],
                'indexes': [models.Index(fields=['kategori'], name='arsip_dokum_kategor_393ef4_idx'), models.Index(fields=['sifat'], name='arsip_dokum_sifat_c084cb_idx'), models.Index(fields=['nomor_dokumen'], name='arsip_dokum_nomor_d_8153a1_idx')],
            },
        ),
    ]
