# Generated by Django 5.0.14 on 2026-07-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='link_view',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
