# Generated by Django 5.0.14 on 2026-07-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0002_dokumen_file_alter_dokumen_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='nomor_terakhir',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nomor Dokumen Terakhir'),
        ),
    ]
