# Generated by Django 5.0.14 on 2026-07-09 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0003_kategori_nomor_terakhir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='status',
            field=models.CharField(choices=[('Berlaku', 'Berlaku'), ('Tidak Berlaku', 'Tidak Berlaku')], default='Berlaku', max_length=15),
        ),
        migrations.AddIndex(
            model_name='dokumen',
            index=models.Index(fields=['status'], name='arsip_dokum_status_115cb6_idx'),
        ),
    ]
