# Generated by Django 5.0.14 on 2026-07-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0004_dokumen_status_dokumen_arsip_dokum_status_115cb6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='status',
            field=models.CharField(choices=[('Draf', 'Draf'), ('Berlaku', 'Berlaku'), ('Tidak Berlaku', 'Tidak Berlaku')], default='Berlaku', max_length=15),
        ),
    ]
