# Generated by Django 5.0.14 on 2026-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0005_alter_dokumen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='file_docx',
            field=models.FileField(blank=True, null=True, upload_to='dokumen_docx/%Y/%m/', verbose_name='File Word (DOCX)'),
        ),
    ]
