# Generated by Django 5.0.14 on 2026-07-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0006_dokumen_file_docx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['urutan', 'nama_kategori'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AddField(
            model_name='kategori',
            name='urutan',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil'),
        ),
    ]
