# Generated by Django 5.0.14 on 2026-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0007_alter_kategori_options_kategori_urutan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='urutan',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan Dokumen'),
        ),
    ]
